CREATE TABLE items(id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(32), price INTEGER);
CREATE TABLE stocks(item_id INTEGER PRIMARY KEY AUTOINCREMENT, amount INTEGER);
CREATE TABLE users(id VARCHAR PRIMARY KEY);


